### ISSUE TITLE
[BUG] mx.random.uniform throws error

### ISSUE THREAD

**Issue by Crear12** [ml-explore/mlx#1005]
**Describe the bug**
I have ```np.random.uniform(-1,0,5)``` that will generate 5 random numbers between -1 and 0, which works. However, ``` mx.random.uniform(-1,0,5)``` returns error 

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: uniform(): incompatible function arguments. The following argument types are supported:
    1. uniform(low: Union[scalar, array] = 0, high: Union[scalar, array] = 1, shape: Sequence[int] = [], dtype: Optional[Dtype] = float32, key: Optional[array] = None, stream: Union[None, Stream, Device] = None) -> array

Invoked with types: int, int, int
```

I also tried to specify the low and high:
```
mx.random.uniform(low=-1,high=2,shape=(15,),dtype=float)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: uniform(): incompatible function arguments. The following argument types are supported:
    1. uniform(low: Union[scalar, array] = 0, high: Union[scalar, array] = 1, shape: Sequence[int] = [], dtype: Optional[Dtype] = float32, key: Optional[array] = None, stream: Union[None, Stream, Device] = None) -> array

Invoked with types: kwargs = { low: int, high: int, shape: tuple, dtype: type }
```

May I ask how to generate some random numbers within a range low and high in mlx? Sorry I'm not so familiar with mlx.

**To Reproduce**
```
mx.random.uniform(low=-1,high=2,shape=(5,),dtype=float)
```
Include code snippet
```
import mlx.core as mx
mx.random.uniform(low=-1,high=2,shape=(5,),dtype=float)
```

**Expected behavior**
I wish it to generate an mx.array with 5 values between -1 and 0 like
```
array([-0.29654096, -0.98023707, -0.93303546, -0.0622353 , -0.15039834])
```

**Desktop (please complete the following information):**
 - OS Version: macOS 14.4.1
 - M1 Max

**Additional context**

**Comment by awni** [comment]
```
import mlx.core as mx
mx.random.uniform(low=-1,high=2,shape=(5,),dtype=mx.float32)
```

Or simply don't specify the `dtype` and it will give you `fp32` by default.
