### ISSUE TITLE
[BUG] AttributeError: type object 'QuantizedLinear' has no attribute 'quantize_module'

### ISSUE THREAD

**Issue by simonw** [ml-explore/mlx#1009]
**Describe the bug**

I'm getting the error `AttributeError: type object 'QuantizedLinear' has no attribute 'quantize_module'` with a fresh install of `mlx-lm` on Python 3.10.10

**To Reproduce**

```bash
python -m pip install mlx-lm
python -m mlx_lm.generate --model mlx-community/Meta-Llama-3-8B-4bit --prompt 'ten fun names for a pet pelican' --max-tokens 256 --temp 0.5
```
After the models have finished downloading I get this stack trace:
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/simon/.local/share/virtualenvs/llm-mlx-IbOvUJP3/lib/python3.10/site-packages/mlx_lm/generate.py", line 148, in <module>
    main(args)
  File "/Users/simon/.local/share/virtualenvs/llm-mlx-IbOvUJP3/lib/python3.10/site-packages/mlx_lm/generate.py", line 112, in main
    model, tokenizer = load(
  File "/Users/simon/.local/share/virtualenvs/llm-mlx-IbOvUJP3/lib/python3.10/site-packages/mlx_lm/utils.py", line 385, in load
    model = load_model(model_path, lazy)
  File "/Users/simon/.local/share/virtualenvs/llm-mlx-IbOvUJP3/lib/python3.10/site-packages/mlx_lm/utils.py", line 343, in load_model
    nn.QuantizedLinear.quantize_module(
AttributeError: type object 'QuantizedLinear' has no attribute 'quantize_module'
```
**Expected behavior**

I expected this to work.

**Desktop (please complete the following information):**
```
mlx==0.11.0
mlx-lm==0.9.0
```
macOS 14.1.1

**Comment by awni** [comment]
I just updated MLX LM to fix this. Try:

`python -m pip install -U mlx-lm`

**Comment by awni** [comment]
If it still doesn't work for you, lmk and I will reopen.

**Comment by simonw** [comment]
Yes! That worked, thanks for the really fast fix.
