### ISSUE TITLE
[BUG] ValueError when loading fused QLoRA model: Parameters not in model

### ISSUE THREAD

**Issue by s-smits** [ml-explore/mlx#1027]
**Describe the bug**
Loading the fused model after QLoRA finetuning and fusion, the code is throwing a ValueError: Received parameters not in model error. This error suggests that there are parameters in the saved weights file that do not match the parameters of the model being loaded.

**To Reproduce**
Run the Python code (unfortunately JSONL could still give problems)

Include code snippet
```python
import subprocess
import sys
import os
from mlx_lm.utils import load, generate
import json
base_model_mlx_4bit = 'mlx-community/Meta-Llama-3-8B-Instruct-4bit'
# Correctly formatted data for the "text" format
finetune_data = {"text": "<|begin_of_text|><|start_header_id|>system<|end_header_id|>You are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>What was the situation like when the narrator first saw Godfrey Norton pacing in the windows of the sitting-room?<|eot_id|><|start_header_id|>assistant<|end_header_id|>The narrator could catch glimpses of Godfrey Norton pacing up and down, talking excitedly, and waving his arms in the windows of the sitting-room. He was in the house about half an hour, and the narrator could see him through the windows.<|eot_id|>"}

# Add to finetune_data folder as jsonl
finetune_data_folder = "finetune_data"
os.makedirs(finetune_data_folder, exist_ok=True)
finetune_data_path = os.path.join(finetune_data_folder, "finetune_data.jsonl")
with open(finetune_data_path, "w") as f:
    json.dump(finetune_data, f)
    f.write("\n")

# Print file content to verify
with open(finetune_data_path, "r") as f:
    file_content = f.read()
    print(f"File content: {file_content}")

qlora_folder = "qlora"
os.makedirs(qlora_folder, exist_ok=True)
print(f"Finetuning {base_model_mlx_4bit} using QLoRA...")
subprocess.run([sys.executable, "-m", "mlx_lm.lora", "--train", "--model", base_model_mlx_4bit, "--data", finetune_data_folder, "--batch-size", "1", "--lora-layers", "16", "--iters", "1", "--save-every", "1", "--max-seq-length", "8192", "--learning-rate", "0.0001", "--adapter-path", qlora_folder], check=True)
print("Fusing the model with the adapter...")
subprocess.run([sys.executable, "-m", "mlx_lm.fuse", "--model", base_model_mlx_4bit, "--adapter-path", qlora_folder, "--save-path", qlora_folder], check=True)

prompt = "<|begin_of_text|><|start_header_id|>system<|end_header_id|>You are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>What was the situation like when the narrator first saw Godfrey Norton pacing in the windows of the sitting-room?<|eot_id|><|start_header_id|>assistant<|end_header_id|>"
model, tokenizer = load(qlora_folder)
generate(model, tokenizer, prompt)
```

```bash
air@MacBook-Air-van-Air test-repo % /opt/homebrew/bin/python3.10 /Users/air/Repositories/test-repo/bug.py
File content: {"text":"<|begin_of_text|><|start_header_id|>system<|end_header_id|>You are a helpful assistant.<|eot_id|><|start_header_id|>user<|end_header_id|>Why did Godfrey Norton shout 'Drive like the devil' to the cab driver?<|eot_id|><|start_header_id|>assistant<|end_header_id|>Godfrey Norton shouted 'Drive like the devil' to the cab driver because he wanted to reach Gross & Hankey's in Regent Street and then the Church of St. Monica in the Edgeware Road in twenty minutes, and he offered half a guinea to the driver if he could do it.<|eot_id|>","question":"Why did Godfrey Norton shout 'Drive like the devil' to the cab driver?","answer":"Godfrey Norton shouted 'Drive like the devil' to the cab driver because he wanted to reach Gross & Hankey's in Regent Street and then the Church of St. Monica in the Edgeware Road in twenty minutes, and he offered half a guinea to the driver if he could do it."}

Finetuning mlx-community/Meta-Llama-3-8B-Instruct-4bit using QLoRA...
Loading pretrained model
Fetching 6 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 70492.50it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Trainable parameters: 0.021% (1.704M/8030.261M)
Loading datasets
Training
Starting training..., iters: 1
Iter 1: Train loss 4.467, Learning Rate 1.000e-04, It/sec 3.411, Tokens/sec 31.724, Trained Tokens 93, Peak mem 5.464 GB
Iter 1: Val loss 3.965, Val took 1.274s
Iter 1: Saved adapter weights to qlora/adapters.safetensors and qlora/0000001_adapters.safetensors.
Saved final adapter weights to qlora/adapters.safetensors.
Fusing the model with the adapter...
Loading pretrained model
Fetching 6 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00, 77195.78it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/Users/air/Repositories/test-repo/bug.py", line 29, in <module>
    model, tokenizer = load(qlora_folder)
  File "/opt/homebrew/lib/python3.10/site-packages/mlx_lm/utils.py", line 385, in load
    model = load_model(model_path, lazy)
  File "/opt/homebrew/lib/python3.10/site-packages/mlx_lm/utils.py", line 349, in load_model
    model.load_weights(list(weights.items()))
  File "/opt/homebrew/lib/python3.10/site-packages/mlx/nn/layers/base.py", line 211, in load_weights
    raise ValueError(f"Received parameters not in model: {extras}.")
ValueError: Received parameters not in model: model.layers.31.self_attn.v_proj.lora_a model.layers.17.self_attn.q_proj.lora_a model.layers.24.self_attn.q_proj.lora_a model.layers.22.self_attn.v_proj.lora_a model.layers.26.self_attn.v_proj.lora_b model.layers.29.self_attn.v_proj.lora_a model.layers.31.self_attn.q_proj.lora_b model.layers.22.self_attn.q_proj.lora_b model.layers.21.self_attn.q_proj.lora_a model.layers.19.self_attn.v_proj.lora_b model.layers.29.self_attn.q_proj.lora_b model.layers.29.self_attn.q_proj.lora_a model.layers.24.self_attn.v_proj.lora_a model.layers.29.self_attn.v_proj.lora_b model.layers.19.self_attn.v_proj.lora_a model.layers.18.self_attn.v_proj.lora_a model.layers.18.self_attn.v_proj.lora_b model.layers.27.self_attn.q_proj.lora_b model.layers.16.self_attn.v_proj.lora_a model.layers.30.self_attn.v_proj.lora_a model.layers.21.self_attn.v_proj.lora_a model.layers.22.self_attn.q_proj.lora_a model.layers.30.self_attn.v_proj.lora_b model.layers.16.self_attn.v_proj.lora_b model.layers.28.self_attn.v_proj.lora_a model.layers.23.self_attn.v_proj.lora_a model.layers.17.self_attn.v_proj.lora_a model.layers.30.self_attn.q_proj.lora_a model.layers.27.self_attn.q_proj.lora_a model.layers.20.self_attn.q_proj.lora_a model.layers.20.self_attn.v_proj.lora_b model.layers.25.self_attn.q_proj.lora_a model.layers.21.self_attn.v_proj.lora_b model.layers.28.self_attn.q_proj.lora_a model.layers.23.self_attn.q_proj.lora_b model.layers.24.self_attn.q_proj.lora_b model.layers.20.self_attn.v_proj.lora_a model.layers.27.self_attn.v_proj.lora_b model.layers.19.self_attn.q_proj.lora_a model.layers.26.self_attn.v_proj.lora_a model.layers.28.self_attn.q_proj.lora_b model.layers.18.self_attn.q_proj.lora_b model.layers.25.self_attn.v_proj.lora_a model.layers.26.self_attn.q_proj.lora_a model.layers.16.self_attn.q_proj.lora_a model.layers.19.self_attn.q_proj.lora_b model.layers.16.self_attn.q_proj.lora_b model.layers.20.self_attn.q_proj.lora_b model.layers.25.self_attn.q_proj.lora_b model.layers.31.self_attn.v_proj.lora_b model.layers.22.self_attn.v_proj.lora_b model.layers.23.self_attn.v_proj.lora_b model.layers.17.self_attn.v_proj.lora_b model.layers.28.self_attn.v_proj.lora_b model.layers.24.self_attn.v_proj.lora_b model.layers.17.self_attn.q_proj.lora_b model.layers.18.self_attn.q_proj.lora_a model.layers.26.self_attn.q_proj.lora_b model.layers.27.self_attn.v_proj.lora_a model.layers.21.self_attn.q_proj.lora_b model.layers.31.self_attn.q_proj.lora_a model.layers.30.self_attn.q_proj.lora_b model.layers.25.self_attn.v_proj.lora_b model.layers.23.self_attn.q_proj.lora_a.
```

**Expected behavior**
Generating tokens after QLoRA finetuning and fusing.

**Desktop (please complete the following information):**
 - OS Version: MacOS 13.6.6
 - mlx version: 0.11.1
 - mlx-lm version : 0.10.0

**Additional context**
Maybe there is a problem with having both the adapter file but also having the fused model in there, however tried to load without fusion file and adapter reference, and did not work as well.

**Comment by awni** [comment]
Fix is in https://github.com/ml-explore/mlx-examples/pull/711
