### ISSUE TITLE
[BUG] ValueError: [Primitive::vjp] Not implemented for ArgReduce. (Porting DINO DETR to MLX)

### ISSUE THREAD

**Issue by sachinraja13** [ml-explore/mlx#1427]
I'm trying to port DINO DETR to MLX.
Original Repo: https://github.com/IDEA-Research/DINO/tree/main
MLX Port: https://github.com/sachinraja13/DINO_DETR_MLX

**To Reproduce**

To run, download and extract the coco 2014 dataset and run this on the terminal:
python main.py \
        --output_dir logs/DINO/R50-MS4 -c config/DINO/DINO_4scale.py --coco_path $coco_path \
        --options dn_scalar=100 embed_init_tgt=TRUE \
        dn_label_coef=1.0 dn_bbox_coef=1.0 use_ema=False \
        dn_box_noise_scale=1.0

While the forward pass works, I'm encountering the following error during gradient computation :

``` 

loading annotations into memory...
Done (t=2.19s)
creating index...
index created!
Start training
Loss Dict:
{'loss_bbox_dn': array(0, dtype=float32), 'loss_giou_dn': array(0, dtype=float32), 'loss_ce_dn': array(0, dtype=float32), 'loss_xy_dn': array(0, dtype=float32), 'loss_hw_dn': array(0, dtype=float32), 'cardinality_error_dn': array(0, dtype=float32), 'loss_ce': array(0.999188, dtype=float32), 'loss_bbox': array(0.558798, dtype=float32), 'loss_giou': array(0.72884, dtype=float32), 'loss_xy': array(0.136371, dtype=float32), 'loss_hw': array(0.422428, dtype=float32), 'cardinality_error': array(892, dtype=float32), 'loss_ce_0': array(1.15137, dtype=float32), 'loss_bbox_0': array(0.552408, dtype=float32), 'loss_giou_0': array(0.687718, dtype=float32), 'loss_xy_0': array(0.0967895, dtype=float32), 'loss_hw_0': array(0.455618, dtype=float32), 'cardinality_error_0': array(894, dtype=float32), 'loss_bbox_dn_0': array(0, dtype=float32), 'loss_giou_dn_0': array(0, dtype=float32), 'loss_ce_dn_0': array(0, dtype=float32), 'loss_xy_dn_0': array(0, dtype=float32), 'loss_hw_dn_0': array(0, dtype=float32), 'cardinality_error_dn_0': array(0, dtype=float32), 'loss_ce_1': array(1.10798, dtype=float32), 'loss_bbox_1': array(0.551652, dtype=float32), 'loss_giou_1': array(0.719414, dtype=float32), 'loss_xy_1': array(0.102286, dtype=float32), 'loss_hw_1': array(0.449366, dtype=float32), 'cardinality_error_1': array(893, dtype=float32), 'loss_bbox_dn_1': array(0, dtype=float32), 'loss_giou_dn_1': array(0, dtype=float32), 'loss_ce_dn_1': array(0, dtype=float32), 'loss_xy_dn_1': array(0, dtype=float32), 'loss_hw_dn_1': array(0, dtype=float32), 'cardinality_error_dn_1': array(0, dtype=float32), 'loss_ce_2': array(1.04032, dtype=float32), 'loss_bbox_2': array(0.572652, dtype=float32), 'loss_giou_2': array(0.720113, dtype=float32), 'loss_xy_2': array(0.111304, dtype=float32), 'loss_hw_2': array(0.461348, dtype=float32), 'cardinality_error_2': array(895, dtype=float32), 'loss_bbox_dn_2': array(0, dtype=float32), 'loss_giou_dn_2': array(0, dtype=float32), 'loss_ce_dn_2': array(0, dtype=float32), 'loss_xy_dn_2': array(0, dtype=float32), 'loss_hw_dn_2': array(0, dtype=float32), 'cardinality_error_dn_2': array(0, dtype=float32), 'loss_ce_3': array(1.0499, dtype=float32), 'loss_bbox_3': array(0.539737, dtype=float32), 'loss_giou_3': array(0.727218, dtype=float32), 'loss_xy_3': array(0.115328, dtype=float32), 'loss_hw_3': array(0.424408, dtype=float32), 'cardinality_error_3': array(895, dtype=float32), 'loss_bbox_dn_3': array(0, dtype=float32), 'loss_giou_dn_3': array(0, dtype=float32), 'loss_ce_dn_3': array(0, dtype=float32), 'loss_xy_dn_3': array(0, dtype=float32), 'loss_hw_dn_3': array(0, dtype=float32), 'cardinality_error_dn_3': array(0, dtype=float32), 'loss_ce_4': array(1.01284, dtype=float32), 'loss_bbox_4': array(0.552064, dtype=float32), 'loss_giou_4': array(0.736284, dtype=float32), 'loss_xy_4': array(0.108989, dtype=float32), 'loss_hw_4': array(0.443075, dtype=float32), 'cardinality_error_4': array(880, dtype=float32), 'loss_bbox_dn_4': array(0, dtype=float32), 'loss_giou_dn_4': array(0, dtype=float32), 'loss_ce_dn_4': array(0, dtype=float32), 'loss_xy_dn_4': array(0, dtype=float32), 'loss_hw_dn_4': array(0, dtype=float32), 'cardinality_error_dn_4': array(0, dtype=float32)}
Traceback (most recent call last):
  File "/Users/sachinraja/Code/DINO_DETR_MLX/main.py", line 265, in <module>
    main(args)
  File "/Users/sachinraja/Code/DINO_DETR_MLX/main.py", line 184, in main
    train_stats = train_one_epoch(
                  ^^^^^^^^^^^^^^^^
  File "/Users/sachinraja/Code/DINO_DETR_MLX/engine.py", line 53, in train_one_epoch
    (loss_value, loss_dict), grads = loss_and_grad_fn(model, samples, targets, criterion, need_tgt_for_training, return_outputs=False)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlx/lib/python3.11/site-packages/mlx/nn/utils.py", line 34, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [Primitive::vjp] Not implemented for ArgReduce.
(mlx)

```

I'm unable to figure out where this error is coming from. I have used mx.argpartition to get indices of the top K scores and corresponding boxes to pick top proposals. Not sure if that's the reason for this error though. Any help would be greatly appreciated. Thanks!

**Additional context**
Using MLX 0.17.3

**Comment by sachinraja13** [comment]
I believe the error is coming from argpartition method itself. Here is the reproducing code:

``` python

import numpy as np
from typing import Optional
import math
import copy
import warnings
import numpy as np
import random
import mlx.core as mx
import mlx.nn as nn
from deformable_transformer_encoder_layer import DeformableTransformerEncoderLayer
from utils import gen_encoder_output_proposals, MLP, _get_activation_fn, gen_sineembed_for_position

    
def _get_encoder_clones(module, N, layer_share=False):
    if layer_share:
        return [module for i in range(N)]
    else:
        modules = []
        for i in range(N):
            modules.append(DeformableTransformerEncoderLayer(**module.params))
        return modules
        


class TransformerEncoder(nn.Module):
    def __init__(self, 
        encoder_layer, num_layers, norm=None, d_model=256, 
        num_queries=300,
        deformable_encoder=False, 
        enc_layer_share=False, enc_layer_dropout_prob=None,                  
        two_stage_type='no'  # ['no', 'standard', 'early', 'combine', 'enceachlayer', 'enclayer1']
    ):
        super().__init__()
        self.params = locals()
        del self.params['self']
        del self.params['__class__']
        # Prepare layers
        if num_layers > 0:
            self.layers = _get_encoder_clones(encoder_layer, num_layers, layer_share=enc_layer_share)
        else:
            self.layers = []
            del encoder_layer

        self.query_scale = None
        self.num_queries = num_queries
        self.deformable_encoder = deformable_encoder
        self.num_layers = num_layers
        self.norm = norm
        self.d_model = d_model

        # Dropout probabilities for each encoder layer
        self.enc_layer_dropout_prob = enc_layer_dropout_prob
        if enc_layer_dropout_prob is not None:
            assert isinstance(enc_layer_dropout_prob, list)
            assert len(enc_layer_dropout_prob) == num_layers
            for prob in enc_layer_dropout_prob:
                assert 0.0 <= prob <= 1.0

        self.two_stage_type = two_stage_type
        if two_stage_type in ['enceachlayer', 'enclayer1']:
            _proj_layer = nn.Linear(d_model, d_model)
            _norm_layer = nn.LayerNorm(d_model)
            if two_stage_type == 'enclayer1':
                self.enc_norm = [_norm_layer]
                self.enc_proj = [_proj_layer]
            else:
                self.enc_norm = [nn.LayerNorm(d_model) for _ in range(num_layers - 1)]
                self.enc_proj = [nn.Linear(d_model, d_model) for _ in range(num_layers - 1)]
            self.class_embed = [nn.Linear(d_model, 91) for _ in range(num_layers - 1)]

    @staticmethod
    def get_reference_points(spatial_shapes, valid_ratios):
        reference_points_list = []
        for lvl, (H_, W_) in enumerate(spatial_shapes):
            H_ = int(H_)
            W_ = int(W_)
            ref_y, ref_x = mx.meshgrid(mx.linspace(0.5, H_ - 0.5, H_, dtype=mx.float32),
                                       mx.linspace(0.5, W_ - 0.5, W_, dtype=mx.float32), indexing='ij')
            ref_y = ref_y.reshape(-1)[None] / (valid_ratios[:, None, lvl, 1] * H_)
            ref_x = ref_x.reshape(-1)[None] / (valid_ratios[:, None, lvl, 0] * W_)
            ref = mx.stack([ref_x, ref_y], axis=-1)
            reference_points_list.append(ref) 
        reference_points = mx.concatenate(reference_points_list, axis=1)
        reference_points = reference_points[:, :, None] * valid_ratios[:, None]
        return reference_points

    def __call__(self, 
            src: mx.array, 
            pos: mx.array, 
            spatial_shapes: mx.array, 
            level_start_index: mx.array, 
            valid_ratios: mx.array, 
            key_padding_mask: mx.array,
            ref_token_index: Optional[mx.array]=None,
            ref_token_coord: Optional[mx.array]=None 
            ):
        """
        Inputs:
            - src: [bs, sum(hi*wi), 256]
            - pos: pos embed for src. [bs, sum(hi*wi), 256]
            - spatial_shapes: h,w of each level [num_level, 2]
            - level_start_index: [num_level] start point of level in sum(hi*wi).
            - valid_ratios: [bs, num_level, 2]
            - key_padding_mask: [bs, sum(hi*wi)]
            - ref_token_index: bs, nq
            - ref_token_coord: bs, nq, 4
        Outputs: 
            - output: [bs, sum(hi*wi), 256]
        """
        if self.two_stage_type in ['no', 'standard', 'enceachlayer', 'enclayer1']:
            assert ref_token_index is None

        output = src

        if self.num_layers > 0 and self.deformable_encoder:
            reference_points = self.get_reference_points(spatial_shapes, valid_ratios)
        intermediate_output = []
        intermediate_ref = []
        if ref_token_index is not None:
            out_i = output[mx.arange(batch_size)[:, None, None], ref_token_index[:, :, None], mx.arange(self.d_model)[None, None, :]]
            intermediate_output.append(out_i)
            intermediate_ref.append(ref_token_coord)

        # Main process across layers
        for layer_id, layer in enumerate(self.layers):
            # Apply dropout for the layer if specified
            dropflag = False
            if self.enc_layer_dropout_prob is not None and random.random() < self.enc_layer_dropout_prob[layer_id]:
                dropflag = True
            
            if not dropflag:
                if self.deformable_encoder:
                    output = layer(src=output, pos=pos, reference_points=reference_points,
                                   spatial_shapes=spatial_shapes, level_start_index=level_start_index,
                                   key_padding_mask=key_padding_mask)
                else:
                    output = layer(src=output.transpose(0, 1), pos=pos.transpose(0, 1), key_padding_mask=key_padding_mask).transpose(0, 1)

            if ((layer_id == 0 and self.two_stage_type in ['enceachlayer', 'enclayer1']) \
                or (self.two_stage_type == 'enceachlayer')) \
                    and (layer_id != self.num_layers - 1):
                output_memory, output_proposals = gen_encoder_output_proposals(output, key_padding_mask, spatial_shapes)
                output_memory = self.enc_norm[layer_id](self.enc_proj[layer_id](output_memory))
                
                # Gather reference tokens
                # ref_token_coord = torch.gather(output_proposals, 1, ref_token_index.unsqueeze(-1).repeat(1, 1, 4))
                topk = self.num_queries
                enc_outputs_class = self.class_embed[layer_id](output_memory)
                # enc_outputs_class_max = enc_outputs_class.max(axis=-1)
                # sorted_indices = mx.argsort(enc_outputs_class_max)
                # ref_token_index = sorted_indices[:, -topk:][:, ::-1]
                ref_token_index = mx.argpartition(enc_outputs_class.max(axis=-1) * -1, topk , axis=1)[:, :topk] 
                # Final gathered output
                ref_token_coord = output_proposals[mx.arange(batch_size)[:, None, None], ref_token_index[..., None], mx.arange(4)[None, None, :]]

                output = output_memory

            # Auxiliary loss
            if (layer_id != self.num_layers - 1) and ref_token_index is not None:
                out_i = output[mx.arange(batch_size)[:, None, None], ref_token_index[:, :, None], mx.arange(self.d_model)[None, None, :]]
                intermediate_output.append(out_i)
                intermediate_ref.append(ref_token_coord)
        # Final normalization
        if self.norm is not None:
            output = self.norm(output)
        # print(intermediate_output)
        if ref_token_index is not None:
            intermediate_output = mx.stack(intermediate_output)
            intermediate_ref = mx.stack(intermediate_ref)
        else:
            intermediate_output = intermediate_ref = None

        return output, intermediate_output, intermediate_ref



encoder_params = {
    'd_model' : 256,
    'd_ffn' : 1024,
    'dropout' : 0.0,
    'activation' : "relu",
    'n_levels' : 4,
    'n_heads' : 8,
    'n_points' : 4,
    'add_channel_attention' : False,
    'use_deformable_box_attn' : False,
    'box_attn_type' : 'roi_align',
}

encoder_layer = DeformableTransformerEncoderLayer(
    **encoder_params
)

# Create an instance of DeformableTransformerEncoder
encoder = TransformerEncoder(
    encoder_layer=encoder_layer,
    num_layers=6,
    norm=nn.LayerNorm(256),
    d_model=256,
    num_queries=300,
    deformable_encoder=True,
    enc_layer_share=False,
    enc_layer_dropout_prob=None,
    two_stage_type='enceachlayer',
)


# Create dummy inputs using NumPy arrays
batch_size = 2
d_model = 256
n_levels = 4
# Define spatial shapes for each level: [height, width]
spatial_shapes_np = np.array([[25, 25], [13, 13], [7, 7], [4, 4]], dtype=np.int64)  # [n_levels, 2]
level_start_index_np = np.concatenate(([0], np.cumsum(np.prod(spatial_shapes_np, axis=1))[:-1]))
total_tokens = int(np.sum(np.prod(spatial_shapes_np, axis=1)))  # total number of tokens

# Create NumPy arrays for inputs
src_np = np.random.randn(batch_size, total_tokens, d_model).astype(np.float32)
pos_np = np.random.randn(batch_size, total_tokens, d_model).astype(np.float32)
valid_ratios_np = np.random.rand(batch_size, n_levels, 2).astype(np.float32)
key_padding_mask_np = np.zeros((batch_size, total_tokens), dtype=bool)  # No padding

src = mx.array(src_np)
pos = mx.array(pos_np)
spatial_shapes = mx.array(spatial_shapes_np, mx.int64)
level_start_index = mx.array(level_start_index_np, mx.int64)
valid_ratios = mx.array(valid_ratios_np)
key_padding_mask = mx.array(key_padding_mask_np)

output, intermediate_output, intermediate_ref = encoder(
    src=src,
    pos=pos,
    spatial_shapes=spatial_shapes,
    level_start_index=level_start_index,
    valid_ratios=valid_ratios,
    key_padding_mask=key_padding_mask
)


def loss_fn(model, 
            src,
            pos,
            spatial_shapes,
            level_start_index,
            valid_ratios,
            key_padding_mask
        ):
    output, intermediate_output, intermediate_ref = model(
        src=src,
        pos=pos,
        spatial_shapes=spatial_shapes,
        level_start_index=level_start_index,
        valid_ratios=valid_ratios,
        key_padding_mask=key_padding_mask
    )
    return intermediate_ref.sum() #+ output.sum() + intermediate_output.sum()


encoder.train()
mx.eval(encoder)
f = nn.value_and_grad(encoder, loss_fn)

loss, grads = f(encoder, src, pos, spatial_shapes, level_start_index, valid_ratios, key_padding_mask)
print(loss)
print(grads)

```

This is the error:

```
Traceback (most recent call last):
 
    loss, grads = f(encoder_mlx, src_mlx, pos_mlx, spatial_shapes_mlx, level_start_index_mlx, valid_ratios_mlx, key_padding_mask_mlx)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlx/lib/python3.11/site-packages/mlx/nn/utils.py", line 34, in wrapped_value_grad_fn
    value, grad = value_grad_fn(model.trainable_parameters(), *args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: [Primitive::vjp] Not implemented for ArgPartition.
```

When I try to compute gradients such that my loss function is output.sum(), I get no error. When I change the loss value to be 
intermediate_ref.sum(), the above error shows up.
