### ISSUE TITLE
[BUG] grad is not computed when calling LoRA-like training target in mx.custom_function

### ISSUE THREAD

**Issue by kaeru-shigure** [ml-explore/mlx#1669]
**Describe the bug**
grad is not computed when calling LoRA-like training target in mx.custom_function

**To Reproduce**

```python
import mlx.core as mx
import mlx.nn as nn

class BaseModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(2, 2)
    def __call__(self, x):
        return self.linear(x)

def create_lora(original_module):
    class LoRA(nn.Module):
        def __init__(self):
            super().__init__()
            self.linear1 = nn.Linear(2, 3)
            self.linear2 = nn.Linear(3, 2)
        def __call__(self, x):
            nonlocal original_module
            print("LORA_called")
            y = self.linear1(x)
            y = self.linear2(y)
            return original_module(x) + y
    return LoRA()

def test_run(model, lora_module, x):
    def loss_fn_wrapped(params, x):
        lora_module.update(params)
        x = model(x)
        x = model(x)
        return x.mean()
    loss, grad = mx.value_and_grad(loss_fn_wrapped)(lora_module.trainable_parameters(), x)

    mx.eval(loss, grad)
    print("loss=",loss)
    print("grad(lora).linear1.weight=",grad["linear1"]["weight"])

def with_cfn(original_fn):
    @mx.custom_function
    def cfn(*args):
        return original_fn(*args)
    @cfn.vjp
    def cfn_vjp(primals, cotangent, output):
        raise RuntimeError("vjp called correctly.")
    return cfn

base_model = BaseModel()
lora_module = create_lora(base_model.linear)
base_model.linear = lora_module

x = mx.random.normal([1, 2])
print("without_custom_fn-------------")
test_run(base_model, lora_module, x)
print("with_custom_fn----------------")
test_run(with_cfn(base_model), lora_module, x)
# mx.value_and_grad is called with lora params,
# and lora is called inside mx.value_and_grad,
# returning the correct loss
# but grad is Zero, and vjp is not called
```

result:
```
without_custom_fn-------------
LORA_called
LORA_called
loss= array(0.494176, dtype=float32)
grad(lora).linear1.weight= array([[-0.61214, -0.00502913],
       [-0.721728, -0.0861656],
       [-0.574084, -0.0290771]], dtype=float32)
with_custom_fn----------------
LORA_called
LORA_called
loss= array(0.494176, dtype=float32)
grad(lora).linear1.weight= array([[0, 0],
       [0, 0],
       [0, 0]], dtype=float32)
```

**Expected behavior**
should compute grad for lora-like training target
```
without_custom_fn-------------
LORA_called
LORA_called
loss= array(0.494176, dtype=float32)
grad(lora).linear1.weight= array([[-0.61214, -0.00502913],
       [-0.721728, -0.0861656],
       [-0.574084, -0.0290771]], dtype=float32)
with_custom_fn----------------
LORA_called
LORA_called
Traceback (most recent call last):
  File "/.../mx.py", line 53, in <module>
    test_run(with_cfn(base_model), lora_module, x)
  File "/.../mx.py", line 30, in test_run
    loss, grad = mx.value_and_grad(loss_fn_wrapped)(lora_module.trainable_parameters(), x)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../mx.py", line 42, in cfn_vjp
    raise RuntimeError("vjp called correctly.")
RuntimeError: vjp called correctly.
```

**Desktop (please complete the following information):**
 - OS Version: MacOS 15.1.1
 - Version: 0.21.1

**Comment by angeloskath** [comment]
I looked into this. I do not think it is a bug but it is indeed confusing. It honestly took me more than 1 hour to figure out what is going on which in hindsight is natural.

A custom function can compute gradients with respect to its inputs only! This means that the way you have implemented the custom function you can compute a custom gradient wrt to the model input and not the model parameters.

I updated the docs in PR #1748. In general I think you have an above average grasp of the way MLX handles modules and gradients etc but my advice would be to try to capture as few things as possible. For instance the way you capture the linear layer to create the lora layer is a bit unintuitive and may cause issues down the line (eg with compile). It would be better to have it as a frozen submodule.

I am inclined to close the issue but feel free to open it again if you think I didn't cover the issue.

**Comment by angeloskath** [comment]
Closing as #1748 was just merged.

**Comment by kaeru-shigure** [comment]
> A custom function can compute gradients with respect to its inputs only!

Thanks! This was the complete answer.
At first I thought I only needed to specify the training target as the first argument (by default) of mx.grad, but it turns out that including that in the arguments of mx.custom_function is also necessary for the gradient to be calculated.
