### ISSUE TITLE
Tests failure when building with nanobind 2.4.0

### ISSUE THREAD

**Issue by zcbenz** [ml-explore/mlx#1703]
I got some `Invalid type  ndarray received` errors when running tests after accidentally built MLX with nanobind 2.4.0, not sure if it is a regression of nanobind.

```
======================================================================
ERROR: test_array_from_noncontiguous_np (test_array.TestArray.test_array_from_noncontiguous_np)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zcbenz/codes/mlx/python/tests/test_array.py", line 697, in test_array_from_noncontiguous_np
    mx_arr = mx.array(np_arr)
ValueError: Invalid type  ndarray received in array initialization.

======================================================================
ERROR: test_dlpack (test_array.TestArray.test_dlpack)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zcbenz/codes/mlx/python/tests/test_array.py", line 1808, in test_dlpack
    self.assertTrue(mx.array_equal(y, x))
                    ~~~~~~~~~~~~~~^^^^^^
ValueError: Invalid type  ndarray received in array initialization.

======================================================================
ERROR: test_diag (test_ops.TestOps.test_diag)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zcbenz/codes/mlx/python/tests/test_ops.py", line 2304, in test_diag
    expected = mx.array(np.diag(x))
ValueError: Invalid type  ndarray received in array initialization.

======================================================================
ERROR: test_put_along_axis (test_ops.TestOps.test_put_along_axis)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/zcbenz/codes/mlx/python/tests/test_ops.py", line 1115, in test_put_along_axis
    idx_mlx = mx.array(idx_np)
ValueError: Invalid type  ndarray received in array initialization.
```

**Comment by awni** [comment]
Hmm.. that's interesting. Non-contiguous NumPy arrays should be [cast to contiguous by Nanobind](https://nanobind.readthedocs.io/en/latest/ndarray.html#overload-resolution).

> When no perfect match can be found, nanobind will try each overload once more while performing basic implicit conversions: it will convert strided arrays into C- or F-contiguous arrays (if requested) and perform type conversion. T

It seems like a nanobind bug. We'll probably need to make a minimal repro and pass it to them to fix.

**Comment by awni** [comment]
File an [issue with Nanobind](https://github.com/wjakob/nanobind/issues/818).. let's see what Wenzel says. We may need a fix in MLX depending or not if the behavior is the new default.
