### ISSUE TITLE
Linear layer is initialized with invalid shape

### ISSUE THREAD

**Issue by ericcanton** [ml-explore/mlx#213]
I am following along with the LoRA readme, and have converted the llama2-7b model to MLX format, saved in `"$WEIGHTS_HOME"/llama/mlx-7b`. 

Now, I'm trying:
```shell
python lora.py --model "$WEIGHTS_HOME"/llama/mlx-7b \
               --train \
               --iters 600
```
Initially, this was crashing at `assert self.vocab_size > 0`. The converted `params.json` for MLX looked like:
```json
{
    "dim": 4096,
    "n_heads": 32,
    "n_layers": 32,
    "norm_eps": 1e-05,
    "vocab_size": -1,
    "n_kv_heads": 32,
    "head_dim": 128,
    "hidden_dim": [
        11008,
        4096
    ]
}
```
(`"vocab_size": -1` came from the `params.json` I got from Meta.) Looking around a bit online, I found [32000](https://github.com/ggerganov/llama.cpp/issues/3900) seemed to be the right literal value for `vocab_size`.

Now running the command above gives this:
```
Loading pretrained model
Traceback (most recent call last):
  File "/path/to/mlx-examples/lora/lora.py", line 353, in <module>
    model, tokenizer = load_model(args.model)
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mlx-examples/lora/lora.py", line 341, in load_model
    model = Model(model_args)
            ^^^^^^^^^^^^^^^^^
  File "/path/to/mlx-examples/lora/models.py", line 171, in __init__
    self.layers = [TransformerBlock(args=args) for _ in range(args.n_layers)]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mlx-examples/lora/models.py", line 171, in <listcomp>
    self.layers = [TransformerBlock(args=args) for _ in range(args.n_layers)]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mlx-examples/lora/models.py", line 145, in __init__
    self.feed_forward = FeedForward(args=args)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/mlx-examples/lora/models.py", line 131, in __init__
    self.w1 = nn.Linear(args.dim, args.hidden_dim, bias=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/mlx-env/lib/python3.11/site-packages/mlx/nn/layers/linear.py", line 30, in __init__
    self.weight = mx.random.uniform(
                  ^^^^^^^^^^^^^^^^^^
TypeError: uniform(): incompatible function arguments. The following argument types are supported:
    1. (low: Union[bool, int, float, complex, object] = 0, high: Union[bool, int, float, complex, object] = 1, shape: List[int] = [], dtype: mlx.core.Dtype = mlx.core.float32, key: Optional[mlx.core.array] = None, stream: Union[None, mlx.core.Stream, mlx.core.Device] = None) -> mlx.core.array

Invoked with: kwargs: low=-0.015625, high=0.015625, shape=([11008, 4096], 4096)
objc[37463]: Invalid or prematurely-freed autorelease pool 0x12b009040. Set a breakpoint on objc_autoreleasePoolInvalid to debug. 
objc[37463]: Invalid autorelease pools are a fatal error
[1]    37463 abort      python lora.py --model "$WEIGHTS_HOME"/llama/mlx-7b --train --iters 600
```

My local machine's details:
- M3 Max MacBook Pro
- macOS Sonoma 14.1.2
- Python 3.11.7, installed through miniconda3 from homebrew.
- `mlx` was installed first from `pip install mlx`, then locally following [the guide](https://ml-explore.github.io/mlx/build/html/install.html#python-api). Unit tests all passed after installation.
- `pip show mlx` gives:
```
Name: mlx
Version: 0.0.5.dev20231218+0e5807b
Summary: A framework for machine learning on Apple silicon.
Home-page: 
Author: MLX Contributors
Author-email: mlx@group.apple.com
License: 
Location: /opt/homebrew/Caskroom/miniforge/base/envs/mlx-env/lib/python3.11/site-packages
Requires: 
```

Let me know if you need any more information! I'm excited about MLX.

**Comment by ericcanton** [comment]
**Update:** I was able to get the LoRA example training by modifying the `__init__` on `Linear`, but there probably is a better way.

Here's the modified snippet of `/opt/homebrew/Caskroom/miniforge/base/envs/mlx-env/lib/python3.11/site-packages/mlx/nn/layers/linear.py`
```python
class Linear(Module):
    r"""Applies an affine transformation to the input.

    Concretely:
    ...
    """
    def _listify_shape(self, io_dims: int | List[int] | Tuple[int]) -> List[int]:
        shape = []
        if isinstance(io_dims, tuple) or isinstance(io_dims, list):
            shape = list(io_dims)
        elif isinstance(io_dims, int):
            shape = [io_dims]
        else:
            raise ValueError(f"io_dims must be tuple or int, got {io_dims}")
        return shape

    def __init__(self, input_dims: int, output_dims: int, bias: bool = True):
        super().__init__()
        input_dims_list = self._listify_shape(input_dims)
        output_dims_list = self._listify_shape(output_dims)
        scale = math.sqrt(1 / math.prod(input_dims_list))
        shape = input_dims_list + output_dims_list
            
        self.weight = mx.random.uniform(
            low=-scale,
            high=scale,
            shape=shape
        )
        # unchanged after

**Comment by awni** [comment]
Huh, I clearly didn't properly test that model. Thanks for reporting this, I will try and make a fix shortly!

**Comment by awni** [comment]
Ok fixes are in https://github.com/ml-explore/mlx-examples/pull/144
